server:
  port: 8080
  servlet:
      context-path: /cotacoes

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 251015
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    genereate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp Santander Dev Week (DIO)
  version: 1.0