server:
  port: 8080
  servlet:
      context-path: /cotacoes

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://mzgdvpevjbpray:b532e9e879e14fdae899480e7330d36b322e6d0b52c15865631727ebdf57c753@ec2-34-198-31-223.compute-1.amazonaws.com:5432/d8kcgfkqhan67n
    username: mzgdvpevjbpray
    password: b532e9e879e14fdae899480e7330d36b322e6d0b52c15865631727ebdf57c753
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp Santander Dev Week (DIO)
  version: 1.0